### ISSUE TITLE
Comparison with other frameworks

### ISSUE THREAD

**Issue by KevinMusgrave** [catalyst-team/catalyst#1066]
What are the benefits of using Catalyst over other PyTorch frameworks? It's hard to decide which one to use, so having a page that shows a comparison would be nice.

**Comment by Scitator** [comment]
Hi,

Yeah, we have a plan for such kind of comparison. At least, we have a [place](https://catalyst-team.github.io/catalyst/getting_started/migrating_from_other.html) for it. It should get ready around next month, I think ;)

Speaking about the features, that's usually hard to compare them right – each of the frameworks would be the best and unique in their opinion. Some of the advantages from my point of view:
- clean codebase, for example check the [code here](https://github.com/catalyst-team/catalyst/blob/dev/catalyst/core/runner.py). As far as I am usually looking for the library's source codes, it's crucial for me, to have it simple and clean. We also have our own [codestyle](https://github.com/catalyst-team/codestyle) too:)
- full reproducibility – we have tested Catalyst pipelines on different machines (but with docker container) and have achieved the same _per-batch_ results. Such kind of things is important for healthcare research.
- powerful [Config](https://github.com/catalyst-team/catalyst/blob/dev/examples/mnist_stages/config.yml) and [Hydra](https://github.com/catalyst-team/catalyst/blob/dev/examples/mnist_stages/config_hydra.yaml) API for complex pipelines. btw, we also have `catalyst-dl tune` for automatic hyperparameter search option with configs support. An [example](https://github.com/catalyst-team/catalyst/blob/dev/examples/mnist_stages/config_tune.yml#L50#L53).
- easy-to-go [Python API](https://colab.research.google.com/github/catalyst-team/catalyst/blob/dev/examples/notebooks/demo%2021xx.ipynb#scrollTo=Mf8I3SW-hYXR) for fast prototyping also included
- as far as you can see, Catalyst support pipeline stages out of the box (which is a kind of unique feature), key-value for loaders/model/critetion/whatever – so, it's easy to work with any number of datasources, rather than train/validation/test only (I can't understand this approach)
- we also support a [large variety of metrics](https://github.com/catalyst-team/catalyst/tree/dev/catalyst/metrics) for CV, NLP and RecSys (tested, of course) with all possible aggerations above them (per-class/micro/macro/weighed/etc), which is important for high-quality results for your RnD.
- and many more - contrib, DDP best practices, amp and apex extensions, etc...
- honestly speaking, just [check the demo](https://colab.research.google.com/github/catalyst-team/catalyst/blob/dev/examples/notebooks/demo 21xx.ipynb), please :)
- or join our slack to continue our conversation ;)

**Comment by KevinMusgrave** [comment]
Thanks for the summary!
