### ISSUE TITLE
[feature] parse tensorboard logs without tensorflow

### ISSUE THREAD

**Issue by Scitator** [catalyst-team/catalyst#130]
@TODO:
- rewrite tensorboard logs parsing
- remove tensorflow dependency

**Comment by velikodniy** [comment]
I'm going to rewrite TB logs parsing, but I'm not sure if it's enough for removing TF from requirements. Also a parser needs compiled `.proto` files and the easiest way to get them is to import them from `tensorboardX` or `tensorboard`. If the support of `pytorch.tensorboard` is planned to be added, I can use `tensorboard` library instead of `tensorboardX`. Anyway it's needed to make `pytorch.tensorboard` work.

I propose:
- add a parser `catalyst.utils.tensorboard.TensorboardEventsReader` (the naming is discussable) that can be used as iterator over events,
- use it instead of `EventAccumulator` in [`catalyst.utils.plotly`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/utils/plotly.py),
- add tests.

Example of usage:

```
events = TensorboardEventsReader(logdir, filters=['scalar'])
for event in events:
    print(event.step, event.time, event.tag, event.value)
```
