### ISSUE TITLE
[fix] fix json metric logger

### ISSUE THREAD

**Issue by Scitator** [catalyst-team/catalyst#134]
@TODO:
- add json formatter to Logger
- check (`import json; data=json.load(open(f'{logdir}/metrics.json')); print(data[-1])`)
- add this check to travis CI

**Comment by hexfaker** [comment]
I suggest adding a check in a form of a test, and not as separate dirty hack. Other tests for loggers would be great as well)

**Comment by TezRomacH** [comment]
It can't be done through `ConsoleLogger` because it can only append text to a file or a stream.
In the case of JSON, we should not only append some texts but also support the format.

Probably we may fix this with some kind of `JsonLogger` class with different logic, but I, personally,  don't think we really need this feature

@Scitator

**Comment by Scitator** [comment]
@TezRomacH @bagxi  Is there any updates, or its better to close the issue?
