### ISSUE TITLE
Version 19.6.3 is broken due to refactoring

### ISSUE THREAD

**Issue by cris** [catalyst-team/catalyst#242]
## Description

I installed a new `19.6.3` version from pip. Trying to run 30 seconds tutorial got such an error:
```
>>> from catalyst.dl.experiments import SupervisedRunner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cris/miniconda3/envs/dl/lib/python3.6/site-packages/catalyst/dl/experiments/__init__.py", line 2, in <module>
    from .core import Experiment, Runner
  File "/Users/cris/miniconda3/envs/dl/lib/python3.6/site-packages/catalyst/dl/experiments/core.py", line 10, in <module>
    from catalyst.dl.state import RunnerState
  File "/Users/cris/miniconda3/envs/dl/lib/python3.6/site-packages/catalyst/dl/state.py", line 6, in <module>
    from catalyst.utils.misc import FrozenClass
ImportError: cannot import name 'FrozenClass'
```

After checking sources looks like `FrozenClass` was moved to `catalyst.utils.frozen`. After fixing import directly in the installed package it started producing a new error:
```
  File "<stdin>", line 1, in <module>
  File "/Users/cris/miniconda3/envs/dl/lib/python3.6/site-packages/catalyst/dl/experiments/__init__.py", line 2, in <module>
    from .core import Experiment, Runner
  File "/Users/cris/miniconda3/envs/dl/lib/python3.6/site-packages/catalyst/dl/experiments/core.py", line 11, in <module>
    from catalyst.dl.utils import UtilsFactory
ImportError: cannot import name 'UtilsFactory'
```
I did not check further and just used `19.6.2`. It worked well.

Looks like `master` already has required fixes, maybe it makes sense to release a new version or remove `19.6.3` because it's broken.

**Comment by Scitator** [comment]
Hi,
Please check the catalyst version and reinstall it with `uninstall`, `install -U` or `--no-cache-use` flags (pip issues). Nevertheless, we have also release 19.06.4 and update `30 seconds tutorial`, thanks!

**Comment by MaisnamNSingh** [comment]
Hi,
I am having trouble importing catalyst. I installed it using pip install -U catalyst on windows 10. I have already installed Pytorch 1.5 before with Cuda 10.1. 

 Below is the error

import os
import torch
from torch.nn import functional as F
from torch.utils.data import DataLoader
from catalyst import dl, metrics
from catalyst.contrib.data.cv import ToTensor
from catalyst.contrib.datasets import MNIST

[Running] python -u "f:\vscode\python\catalyst.py"
Traceback (most recent call last):
  File "f:\vscode\python\catalyst.py", line 5, in <module>
    from catalyst import dl, metrics
  File "f:\vscode\python\catalyst.py", line 5, in <module>
    from catalyst import dl, metrics
ImportError: cannot import name 'dl' from partially initialized module 'catalyst' (most likely due to a circular import) (f:\vscode\python\catalyst.py)
Can somebody help me with this error.

Just importing pytorch is working below

import os
import torch
from torch.nn import functional as F
from torch.utils.data import DataLoader

[Running] python -u "f:\vscode\python\catalyst.py"

[Done] exited with code=0 in 0.836 seconds
No error importing pytorch.

**Comment by roboserg** [comment]
Same, having an issue:

ImportError                               Traceback (most recent call last)
[<ipython-input-29-8c0b06396907>](https://localhost:8080/#) in <module>()
----> 1 from catalyst.utils import trace
      2 
      3 if is_fp16_used:
      4     model = trace.load_traced_model(
      5         f"{logdir}/trace/traced-forward-opt_O1.pth",

ImportError: cannot import name 'trace' from 'catalyst.utils' (/usr/local/lib/python3.7/dist-packages/catalyst/utils/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by Scitator** [comment]
Hi,
don't you mind to open a new issue?
thanks in advance!
