### ISSUE TITLE
Triplet loss epic

### ISSUE THREAD

**Issue by ermakovpetr** [catalyst-team/catalyst#459]
best triplet loss ever

https://github.com/adambielski/siamese-triplet
https://github.com/andreasveit/triplet-network-pytorch
https://github.com/CoinCheung/triplet-reid-pytorch
https://discuss.pytorch.org/t/triplet-loss-in-pytorch/30634

**Comment by ermakovpetr** [comment]
@Scitator Assigne

**Comment by smivv** [comment]
@ermakovpetr, @Scitator, almost done metric learning with catalyst and triplet loss. I can help if needed :)

**Comment by Scitator** [comment]
@smivv Sure, do you have a pipeline proposal or something like that?

**Comment by smivv** [comment]
@Scitator yeah, since I am working with metric learning, I have already implemented:

1. Triplet loss class (taken from [here](https://github.com/NegatioN/OnlineMiningTripletLoss))
2. Callback class to measure accuracy using kNN algorithm.

I can already create pull request for the triplet loss, but callback, at least for me, seems to be very specific to my case.

What I'd like to do is to implement generic solution for many cases.

I've seen [Pull Request](https://github.com/catalyst-team/catalyst/pull/433) where you proposed to implement generic `DatasetMetricCallback` class in order to collect some data during `on_batch_end` and do some additional calculations `on_loader_end`. So I think what I can do is to implement this class.

But I have some things which are unclear for me:

1. Could you tell me the best template in `contrib/criterion/` folder, so I will adapt my loss code to it.
2. What would be the best structure for the generalization of Callback and Meter? Whether Callback or Meter could be generalized, depends on where we want put metric logic.

**Comment by Scitator** [comment]
@smivv Hi,
Could you please create a PR, so we can check all the features?
For now, I don't think we have some special criteria.... for criterions :)
Or Callbacks... if your Callback is too specific, our contrib is always open, so we can try it there

**Comment by smivv** [comment]
@Scitator, agreed! By the way I will split the whole metric learning pipeline to several PRs.

**Comment by smivv** [comment]
@Scitator, this issue can be closed.

**Comment by Scitator** [comment]
@smivv but there was only one PR.... :)

**Comment by smivv** [comment]
@Scitator, I thought this issue related only to triplet loss, but now I got you ;)

**Comment by Scitator** [comment]
@smivv what would be an appropriate name for this initiative? could you please share, what next steps do you see?

**Comment by smivv** [comment]
@Scitator, I am already working on knn metric callback and feature collection meter.
I am just thinking maybe it is possible to derive that classes from others that are already exists in order to do not add complexity to the repository or maybe create very generic ones?

**Comment by Scitator** [comment]
@smivv Is it okay for you to add your Callback to Catalyst.contrib? By this way, we can easily check the it and guide about its development. Maybe, make it more general :)

**Comment by smivv** [comment]
@Scitator, please see [PR](https://github.com/catalyst-team/catalyst/pull/560)

**Comment by Scitator** [comment]
Is Epic done? @smivv

**Comment by smivv** [comment]
@Scitator, I think only notebook left, I was waiting for the release.

**Comment by Scitator** [comment]
looks like ~done :)
