### ISSUE TITLE
run catalyst-dl trace /logs  report   config.json doesn't exist!

### ISSUE THREAD

**Issue by lgqfhwy** [catalyst-team/catalyst#485]
Hello, when I run [segmentation example](https://github.com/catalyst-team/catalyst/blob/master/examples/notebooks/segmentation-example.ipynb), It only generate checkpoint, so when I run catalyst-dl trace /logs, it report: Exception: Path '/logs/configs/_config.json' doesn't exist!
 I find that when I run this [segmentation example](https://github.com/catalyst-team/catalyst/blob/master/examples/notebooks/segmentation-example.ipynb), it does not need config.json, however,  catalyst does not generate _config.json in log directory. So when I run catalyst-dl would report error.
Please tell me when I write code like [segmentation example](https://github.com/catalyst-team/catalyst/blob/master/examples/notebooks/segmentation-example.ipynb), how to generate config.json for catalyst-dl trace?
Thank you so much!

**Comment by jchen42703** [comment]
Related: #430. As far as I know, there isn't an easy way to do it unless you used catalyst's config/experiments API (i.e. through [mlcomp](https://github.com/catalyst-team/mlcomp) or something like [this](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/scripts/run.py)). This is because `__config.json` is made through `catalyst.utils.config.dump_environment` which is dependent on an Experiment config. You could maybe look into [`catalyst.dl.utils.trace.trace_model`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/utils/trace.py) to do it without `__config.json`.

**Comment by lgqfhwy** [comment]
Ok. thank you so much!

**Comment by Scitator** [comment]
Looks like solved :)
