### ISSUE TITLE
Tensorboard logs start at a non-zero step

### ISSUE THREAD

**Issue by YaLTeR** [catalyst-team/catalyst#755]
**Describe the bug**
Tensorboard logs start at a non-zero step.

**To Reproduce**

Just run one of the showcase colab notebooks, e.g. https://colab.research.google.com/github/catalyst-team/catalyst/blob/master/examples/notebooks/classification-tutorial.ipynb (you will need to replace multiple `pip install` invocations in the second cell with a single one to fix issues with dependencies: `!pip install -U albumentations pretrainedmodels catalyst tensorflow`).

**Expected behavior**
The step starts at 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/1794388/79219556-2cfb1e80-7e5b-11ea-8de5-2407c14faebb.png)

**Additional context**
I believe the issue is in the following code:
https://github.com/catalyst-team/catalyst/blob/2ede5354b2a02807b3c1c69fc0718351382c8301/catalyst/core/runner.py#L391-L394
When `global_step` is supposed to be zero at the very start it is instead set to the value it would have after 1 epoch (since `global_epoch` starts at 1).

**Comment by Scitator** [comment]
We are using one `global step` for both `train` and `validation` loaders. By this way, your **validation** plots shifts a bit. Nevertheless this allows to to check your batch metrics plots easily.

**Comment by yhn112** [comment]
Sorry, @Scitator, it seems you don't quite understand the issue. 

The value of state.global_step equals the length of the training dataset **before** the beginning of the first epoch. (After the first epoch it equals doubled length of the training dataset and so on).
The initial value of `state.global_step` is 0 and the initial value of `state.global_epoch` is 1, as a result, the code mentioned in the issue has this effect.

This has nothing to do with the validation loader and the fact that you have a single step counter for both loaders.

**Comment by yhn112** [comment]
I have a couple of somehow related questions.

First of all, just curious, what the piece of code mentioned in the issue was supposed to do?
Also, in documentation is said that `state.global_step` is
> numerical indicator, counter for all batches

and I agree, "number of steps" most often means "number of butches". But in reality, it counts the number of individual samples, not batches. IMHO, it's worth changing the current behavior to counting batches, don't you think so? (Probably it's even better to have separate counters for counting samples and batches).

I can make a PR with these changes.

P.S.The current counting of samples is incorrect in any case because the size of batches can vary. (at least for the last batch in the loader)

**Comment by Scitator** [comment]
@yhn112 Issue confirmed, thanks for explanation.
I would be glad, if you could make a PR with required fixes.
Nevertheless, sample-based logging used to have an opportunity to compare pipelines with different batch_size correctly. In this way you directly measure the number of `data` passed through the network.
