### ISSUE TITLE
installation fails on crc32c setup (Windows 10)

### ISSUE THREAD

**Issue by evfro** [catalyst-team/catalyst#779]
System info:
```
Windows 10 ver.1903, x64
python ver. 3.8.3, build MSC v.1916 64 bit (using conda)
```
Running `pip install -U catalyst` fails at the `crc32` setup stage:
```bash
Building wheel for crc32c (setup.py) ... error
  ERROR: Command errored out with exit status 1:
...
ERROR: Failed building wheel for crc32c
```

Apparently, the `crc32` module doesn't build against Visual Studio, see https://github.com/ICRAR/crc32c/issues/1. However, VS builds are default on Windows systems for python.

I wonder if the `crc32c` module is necessary at all. For example, there's some crc32 functionality in the `binascii` module, e.g.:
```python
import binascii
buf = open("my_file.zip","rb").read()
print( binascii.crc32(buf))
```
Wouldn't it be sufficient? Thanks!

**Comment by Scitator** [comment]
Hi,
Good catch, we will check this issue during next release.
I hope, we could also write to @velikodniy as tbparser creator.

Meanwhile, do you have you problems with unix-based operation systems?

**Comment by evfro** [comment]
@Scitator hi, thanks.

Well, actually, I don't have problems on Windows 10 either after installing recent VS C++ build tools. But it requires +1.4Gb of storage, which seems to be an overkill for supporting a little 3rd party crc32 tool.

**Comment by velikodniy** [comment]
CRC32 and CRC32C are slightly different algorithms so that we can't simply replace `crc32c` with `binascii`. Although the computation is the same, CRC32C uses a different polynomial, and the results are different. I used `crc32c` instead of pure-Python implementation because crc32c is a highly optimized library that can use the CRC32C instruction from the SSE 4.2 set (if it is available). It's normal for tensorboard logs to be huge, so speed matters. 
That is strange that you couldn't install it on Windows. As far as I can see, the wheels in the [PyPI repository](https://pypi.org/project/crc32c/#files) contain precompiled binaries, and there is no need to have Visual Studio installed at all. I would advise you to create an issue for [`crc32c`](https://github.com/ICRAR/crc32c) if the problem persists.
As a workaround, we can remove crc32c from dependencies at all. We can use  `crc32c` if it's installed and pure-Python (and slow) implementation if not.
@Scitator what do you think?

**Comment by Scitator** [comment]
@velikodniy What do you think about `crc32c` use if it's installed and pure python `crc32c` one if not. Our contrib tensorflow parser already have similar logic for tensorboard writer.
There should be simple `if-else` condition somewhere here :)
github.com/catalyst-team/catalyst/blob/master/catalyst/contrib/utils/tools/tensorboard.py#L14#L16

**Comment by velikodniy** [comment]
> What do you think about crc32c use if it's installed and pure python crc32c one if not.

It's exactly what I proposed. :)

**Comment by velikodniy** [comment]
Oh! I've just realized that I implemented it already in `tensorboardX` https://github.com/lanpa/tensorboardX/pull/429. 😄 We can use `crc32c` from this library until we drop it from dependencies and replace with `torch.tensorboard` (if we do).

So, all we need is ~love~ to replace this one

```
if os.environ.get("CRC32C_SW_MODE", None) is None:
    os.environ["CRC32C_SW_MODE"] = "auto"
from crc32c import crc32 as crc32c  # noqa: E402
```

with this one:

```
from tensorboardX.crc32c import crc32c
```

Don't forget to remove `crc32c` from the dependencies and make a note in the README file about speedup if the library is installed.

**Comment by Scitator** [comment]
@evfro would you like to make your first time contribution into project?
Based on current discussion, it should be easy to do, and I would be glad to welcome new contributor :)

**Comment by Scitator** [comment]
@evfro How are you? what do you think about my proposal?

**Comment by evfro** [comment]
@Scitator sorry, this month is densely packed for me. I can try in June if I'll find some spare time.

**Comment by Scitator** [comment]
fixed during https://github.com/catalyst-team/catalyst/pull/872
