### ISSUE TITLE
Code Architecture Enforcement

### ISSUE THREAD

**Issue by ssakhavi** [catalyst-team/catalyst#804]
## 🚀 Feature Request
Enforcing the structure of the code 

### Motivation
In many collaborative projects or even projects that explore a certain dataset with multiple annotations, one of the features that is useful is enforcing to the developers in how to present the final code. 

This will result in code readability and cleaner code and faster validation and visualization.
I am not proposing that the current structure to change, but rather, I am proposing that there is also an option where a single object can be defined and then passed to a single function for training. 

### Proposal
In the following, I refer to the [advanced segmentation code](https://github.com/catalyst-team/catalyst/blob/master/examples/notebooks/segmentation-tutorial.ipynb).

In the `runner` object, when using the `train` method, the following arguments are given: 
```
runner.train(
    model=model,
    criterion=criterion,
    optimizer=optimizer,
    scheduler=scheduler,
    # our dataloaders
    loaders=loaders,
    # We can specify the callbacks list for the experiment;
    callbacks=callbacks,
    # path to save logs
    logdir=logdir,
    num_epochs=num_epochs,
    # save our best checkpoint by IoU metric
    main_metric="iou",
    # IoU needs to be maximized.
    minimize_metric=False,
    # for FP16. It uses the variable from the very first cell
    fp16=fp16_params,
    # prints train logs
    verbose=True,
)
```
I propose that some of the arguments are encapsulated into a single object and then passed to this method or the training method called on the new object. Let's call the new object `ExperimentObject` (I'm sure you guys can come up with a better name).

```
class MyExperiment(ExperimentObject):
  __init__(self):
  self.experiment_name = ...

  _get_model(self):
   ....
  return model
 _get_data_loader(self):
  ...
 return loader
_get_valid_visualization(self):
# This method is for inference





# And eventually:

runner.train(MyExperiment, ...)
# or 
MyExperiment.train()

# For visualization of the results (e.g. 3 Random Images):
MyExperiment.visualize_valid(random=true,number=3)
```

### Alternatives
This feature is an extended version to the structure proposed in pytorch lightning and believe this extra feature can boost the usage of catalyst.

**Comment by Scitator** [comment]
Hi, thank you for proposal.... it's interesting :)

Catalyst already have 4 **core** parts separated:
- Experiment
- Runner
- Callback
- State

you can read more about them [here](https://catalyst-team.github.io/catalyst/api/core.html#experiment).

---

Meanwhile, our **DL** part is only user-friendly interface for these 4 components. For example, you can see `Experiment` creation under [`.train`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/runner/core.py#L134#L157)(quite strain-forward code, I suppose). Then we have just a bunch of for-loops encapsulation during [`run_experiment`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/runner/core.py#L134#L157), like 
![loop](https://github.com/catalyst-team/catalyst-pics/raw/master/pics/train_loop.png)
(btw, Catalyst is the only framework with stages support)

So, generally speaking you can easily create an instance of your own [`_Experiment`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/core/experiment.py#L13) and use
```
experiment = MyCustomExperiment(_Experiment)
runner.run_experiment(experiment)
```
easy, isn't it? We think so too. 

---

Such design gave us an opportunity to create [`ConfigExperiment`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/experiment/config.py) for example, where you can incapsulate your whole experiment into config files. A bit [tricky example](https://github.com/catalyst-team/catalyst/blob/master/tests/_tests_cv_classification_transforms/config2.yml), but it shows, how you can parametrise... **everything**. The run command is still very simple:
```
catalyst-dl run -C=/path/to/config
```
or, we could also use, something like
```
catalyst-dl run -C=/path/to/config1 /path/to/config2 /path/to/config3
```
to reparametrise `config1` with `config2` and `config1+config2` with `config3`.

---

Finally, we could even reparametrise some parts of the config through command line interface:
```
catalyst-dl run -C=/path/to/config \
  --stages/criterion_params/criterion="BCEWithLogitsLoss":str
```
In this case you will use `BCEWithLogitsLoss` during training instead of config-defined `CrossEntropyLoss` for [this example](https://github.com/catalyst-team/catalyst/blob/master/tests/_tests_cv_classification_transforms/config2.yml).

And yes, you can do something like
```
catalyst-dl run -C=/path/to/config1 /path/to/config2 /path/to/config3 \
  --stages/criterion_params/criterion="BCEWithLogitsLoss":str
```
easily.

And yes, your final training config will be saved under `/logdir/_config.json` to ensure reproducibility.
